{% set version = "0.2" %}

package:
  name: depi
  version: {{ version }}

source:
  url: https://github.com/OpenSMFS/depi/archive/{{ version }}.tar.gz
  sha256: 044ff7685d34f55379780f801834074de92c0690affd7e5b54ae26aaa559f200

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib
    - seaborn
    - pandas
    - ipython
    - joblib

test:
  imports:
    - depi

about:
  home: https://opensmfs.github.io/depi/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Diffusion-Enhanced Photon Inference for single-molecule FRET experiments'
  description: |
    Monte-Carlo Diffusion-Enhanced Photon Inference (MC-DEPI) is a method
    to simulate solution-based single-molecule FRET experiments and to estimate
    physical parameters from experimental data. Paper describing the method
    <https://doi.org/10.1101/385252>.
  doc_url: https://github.com/OpenSMFS/depi
  dev_url: https://github.com/OpenSMFS/depi

extra:
  recipe-maintainers:
    - tritemio
